camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Xusen
  filter:
    create: All tasks
  database:
    type: mysql
    
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://iotuser:CF7hqp*Y@172.16.1.33:11000/eureka/,http://iotuser:CF7hqp*Y@172.16.1.34:11000/eureka/
  instance:
      prefer-ip-address: true
      status-page-url-path: /swagger-ui.html
      
spring:
  application:
    name: camunda-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/camunda_demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Dap1234$
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000