server:
  port: 8888

spring:
  application:
    name: MICROSERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://iotuser:CF7hqp*Y@172.16.1.33:11000/eureka/,http://iotuser:CF7hqp*Y@172.16.1.34:11000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}